# /frontend/nginx.conf
server {
    listen 80;           
    root /usr/share/nginx/html; 
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }

    # 🚀 추가
    location /artist/ {
        proxy_pass http://localhost:3000;
    }
}